### ISSUE TITLE
Issues with embed input selection in Firefox

### ISSUE THREAD

**Issue by crobertsbmw** [vriteio/vrite#18]
Editing source links for youtube or code pen doesn't work well. It seems there no cursor? If I misspell youtube or something, then I pretty much have to delete all the text and re-paste it in. I can't highlight the text or anything either. I would expect this to work like any other text input.

**Comment by crobertsbmw** [comment]
It does look like I can use the arrow keys to get a cursor, but I can't use my mouse.

**Comment by areknawo** [comment]
Seems to be working for me. Can you share a screenshot or a short video?

https://github.com/vriteio/vrite/assets/10221873/f30673ac-11c1-4258-abf2-16ef02a3f19f

**Comment by crobertsbmw** [comment]
I'm using https://editor.vrite.io/
And it seems to work on Chrome, but not firefox.
https://github.com/crobertsbmw/garbage/blob/main/screen_record.mov

**Comment by areknawo** [comment]
Indeed this seems to be an issue on Firefox. Thanks for reporting this. Will work on fixing this and testing Firefox support more.

**Comment by areknawo** [comment]
Turns out Firefox has issues with selection in `[draggable=true]` contained inputs (https://bugzilla.mozilla.org/show_bug.cgi?id=800050). Since there were issues with dragging on other browsers as well (especially on the mobile ones with newly-added support) it was disabled for now. Thus, input selection should work fine.

I will keep this bug in mind for the future, and will likely implement a different kind of dragging mechanism.
