### ISSUE TITLE
Easy self-hosting support

### ISSUE THREAD

**Issue by michaelb** [vriteio/vrite#21]
I noticed there aren't any instructions for self-hosting Vrite, which is somewhat uncommon for such "open-source" projects

Is it officially 'supported' ?

Note: if Vrite is your business, self-hosting may not be incompatible. Standard Notes comes to mind as an example of open-source, self-hostable but tiered service

**Comment by areknawo** [comment]
Hey,
Self-hosting isn't officially supported right now.

The thing is, Vrite originally started as a closed-source service, and I decided a bit later in the development that open-source is the best way for such a CMS to evolve (as you've said, there are many COSS projects with viable business models).

That's why it wasn't optimized for that from the start and needs some work to do so. Now, with updates and bug fixes coming pretty often, it's not currently prioritized as the hosted platform allows me to iterate a bit quicker.

That said, self-hosting is a must-have for a stable version and I'm working on a data migration system as well to make it really simple for those who do want to move over.

More details on all that are here: https://docs.vrite.io/self-hosting/

**Comment by ile** [comment]
Hi,

I'm trying to get this to work, but I have some trouble. 

For example, there are two similar/same lines, which seem to cause some problems ("address already in use"):

https://github.com/vriteio/vrite/blob/main/apps/backend/app/src/index.ts#L8
https://github.com/vriteio/vrite/blob/main/apps/backend/api/src/index.ts#L19

Any help, please?

**Comment by areknawo** [comment]
The work for self-hosting is almost completed on the [feature/self-hosting](https://github.com/vriteio/vrite/tree/feature/self-hosting) branch. Many changes were made to simplify the process and fix issues like the ones you're experiencing.

I'm still working on documentation and a proper build pipeline, but `docker-compose.yml` and `Dockerfile`s are already available there.

I'd recommend you wait until it's all ready and merged (hopefully sometime this week), but feel free to check it out if you're interested.

**Comment by areknawo** [comment]
Self-hosting is now supported with v0.2.0, using Docker and Docker Compose. Check out the official guide here: https://docs.vrite.io/self-hosting/docker/

Will close this one, but please report any self-hosting problems as separate issues.
Thanks!
