### ISSUE TITLE
Feat: add deploy button to trigger a webhook

### ISSUE THREAD

**Issue by kcoderhtml** [vriteio/vrite#26]
I personally use Netlify to host my sites, but if I do some shuffling of my pages, then 3-4 or more builds can all be triggered. An optional addition to the webhooks could be to have a period that it waits for any more changes before triggering.

**Comment by areknawo** [comment]
Yeah, that can be a problem in certain cases. I have a few ideas on how to fix it, with different pros and cons.

I was thinking of a system where Webhooks run in 30s or 1 min after the actual event, with the user getting a Notification in the dashboard with options to "Run now" or "Cancel". That said, with Webhooks being triggered on the backend (also in response to changes made through API), it's a bit tricky to implement.

Other solution would be some sort of batching, where the wait period is longer, but all changes made in certain time window come as one. That said, in case you want the Webhooks to run immediately (or relatively fast), batching will stand in the way.

It's possible to add a different button/trigger that could be connected to a different Webhook and run manually, e.g. on click. The drawbacks are - you lose a degree of automation, and have to use this trigger instead of just working with the content.

**Comment by areknawo** [comment]
Will think on this and likely implement some kind of combination of all mentioned solutions. That said, it's not on the immediate roadmap for now.

**Comment by kcoderhtml** [comment]
Awesome! Thanks.

**Comment by areknawo** [comment]
I thought deeply about implementing it in v0.4. Ultimately I decided not to, due to the following reasons:
- In general, batching adds complexity that's unnecessary for something like Webhooks.
- Batch can contain already outdated webhook data, which would have to be handled either by Vrite or the client;
- Delay/debounce has similar disadvantages to batching (just without sending the batched data);
- Any kind of UI to cancel/run webhooks will be distracting (especially in collaborative space, where it'd run continuously);

Your issue should instead be handled by a system like Changesets (#57) - a WIP concept for applying multiple changes to a workspace at once;

**Comment by kcoderhtml** [comment]
That seems like a perfect solution! That basically accomplishes what I wanted with the webhooks button.
