### ISSUE TITLE
self-hosted: cannot log in

### ISSUE THREAD

**Issue by ovizii** [vriteio/vrite#40]
So after a long journey of finally enabling SMTP without authentication, I managed to receive the email to validate my email. I clicked the link, I was told my email is now verified and there was a link to click to visit the dashboard. Clicking that link sends me to http://10.10.10.10:7171/auth and asks me to log in. 

Login doesn't work with user/pass. The page accepts my credentials and then redirects me here again: http://10.10.10.10:7171/auth 

When I simply visit the login page I already see these errors:

![image](https://github.com/vriteio/vrite/assets/837902/6fcd2ee8-3095-48b0-b154-8c5008c0b84b)

I tried logging in via magic link, I receive the login link but upon opening it, I have the exact same behaviour as above with user/pass.

docker compose logs -f does show absolutely no reaction when this happens so I cannot suzpply any logs.

**Comment by areknawo** [comment]
Do you have the following env vars set?

```
PUBLIC_COLLAB_URL=
PUBLIC_APP_URL=
PUBLIC_API_URL=
PUBLIC_ASSETS_URL=
```

They should reflect the URLs your services are accessible at, e.g. `PUBLIC_APP_URL=http://10.10.10.10:7171`

You can also try setting the following to explicitly specify the `Domain` attribute for auth cookies (which might be the source of the issue):

```
COOKIE_DOMAIN=10.10.10.10
```

**Comment by ovizii** [comment]
Thanks, the tip with the cookie domain solved the problem. 
I already had the URLs set in my .env file. 

I have a related question about those URLs: if I put my vrite instance behind a reverse proxy, which of those URLs needs to be publicly accessible? Is it just PUBLIC_APP_URL? I assume the others only need to be accessible to each other and not from "outside"?

**Comment by areknawo** [comment]
For now, all need to be accessible from the outside. To give you an overview:
- `PUBLIC_APP_URL` is the main one (where you access the dashboard)
- `PUBLIC_API_URL` is for API access (which is also sometimes used by the APP, but you'd likely want to be accessible outside anyway)
- `PUBLIC_COLLAB_URL` is a dedicated WebSocket server to support collaboration, primarly in the editor. It applies even if you only use it for yourself, as it receives and saves edits in real time.
- `PUBLIC_ASSETS_URL` serves uploaded assets, i.e. images. Recently, it also supports URL params for image optimization - `format`, `w` (width), `h` (height), and `fit`.

It's how it was originally structured, partially due to technical limitations and partially to better suit the Vrite Cloud setup. I'm not planning to change it right now, but I might try to optimize it for v1.
