### ISSUE TITLE
I18n Support

### ISSUE THREAD

**Issue by obetomuniz** [vriteio/vrite#7]
What about offer built-in I18n support for content pieces?

It could be some kind of extension, Idk. But would be great if the UI offer a smooth experience to create posts in multiple languages.

I know that, as a write, I can use metadata to flag the post language somewhat, but have it in UI level could be an excellent difference and set Vrite as an international product. 

Thoughts?

**Comment by areknawo** [comment]
I think a general "content piece variants" feature would be a good approach to support i18n and other similar use-cases. 

Users could have the "base variant" and then create new ones that "extend" it, customizing base metadata and content further.

**Comment by obetomuniz** [comment]
That's even more powerful than my initial proposal. Loved it. Is it similar to Custom Post Types in WordPress?

**Comment by areknawo** [comment]
I'm not really a WP user so I can't surely say. The idea is mostly inspired by Strapi: https://docs.strapi.io/user-docs/content-manager/translating-content, though:
- I'm using the term "variant" rather than "version" as I have other plans for versioning in Vrite;
- It's more general than just for i18n (though I imagine it would be the primary use-case)

For more descriptive example: you have the *English* base with content and metadata like title and date. Then you have e.g. a *German* variant where you change the content and title to fit the language, but leave other details like date the same. All variants would be related to a single content piece and easy to switch between from the UI or the API.

**Comment by areknawo** [comment]
I18n is now supported through Variants, from v2023.7.17. If you have any feedback feel free to leave it in Discussions and report any bugs in separate Issues. Thanks!
